name: Release ArrangeDependencies.Autofac.MemoryCache

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ github.event.inputs.version }}
      - name: Test
        run: dotnet test --configuration Release /p:Version=${{ github.event.inputs.version }} --no-build
      - name: Pack
        run: dotnet pack ArrangeDependencies.Autofac.MemoryCache --configuration Release /p:Version=${{ github.event.inputs.version }} --no-build --output .
      - name: Push
        run: dotnet nuget push ArrangeDependencies.Autofac.MemoryCache.${{ github.event.inputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}